### ISSUE TITLE
Bankstack gets confused with new Reagent Bag

### ISSUE THREAD

**Issue by layzsmurf** [kemayo/wow-bankstack#6]
With the event I purchased a 20 slot reagent bad and both Backstack and the Blizzard UI choke on it.
[Storm Battered reagent bag](https://www.wowhead.com/item=202188/storm-battered-reagent-bag)

Blizzard "clean up bags" simply ignores it and puts crafting materials stored in it into normal bags defeating the bag completely.

Bandstack willl get "confused" during sorting.

**Comment by kemayo** [comment]
https://github.com/Stanzilla/WoWUIBugs/issues/349 suggests that the new reagent slot might not be getting appropriate API returns at the moment, which probably isn't helping.

**Comment by layzsmurf** [comment]
The newest release has fixed the issue.
