### ISSUE TITLE
Error when profession bag is equipped

### ISSUE THREAD

**Issue by astavitsky-nybc** [kemayo/wow-bankstack#7]
This appears to only happen when I have a profession bag equipped:

Message: Interface/AddOns/BankStack/core.lua:489: attempt to call global 'GetContainerNumFreeSlots' (a nil value)
Time: Mon Nov 21 14:39:53 2022
Count: 1
Stack: Interface/AddOns/BankStack/core.lua:489: attempt to call global 'GetContainerNumFreeSlots' (a nil value)
[string "@Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua"]:769: in function <...Ons/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:725>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `GetContainerNumFreeSlots'
[string "@Interface/AddOns/BankStack/core.lua"]:489: in function `CanItemGoInBag'
[string "@Interface/AddOns/BankStack/fill.lua"]:66: in function `Fill'
[string "@Interface/AddOns/BankStack/sort.lua"]:35: in function <Interface/AddOns/BankStack/sort.lua:12>
[string "@Interface/AddOns/BankStack/core.lua"]:558: in function `?'
[string "@Interface/AddOns/BankStack/ldb.lua"]:68: in function `OnClick'
[string "@Interface/AddOns/BankStack/lib/LibDBIcon-1.0/LibDBIcon-1.0.lua"]:144: in function <...AddOns/BankStack/lib/LibDBIcon-1.0/LibDBIcon-1.0.lua:142>

Locals: errMsg = "Interface/AddOns/BankStack/core.lua:489: attempt to call global 'GetContainerNumFreeSlots' (a nil value)"
isBugGrabber = nil
tsmErrMsg = nil
oldModule = nil
private = <table> {
 globalNameTranslation = <table> {
 }
 FormatErrorMessageSection = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:525
 ErrorHandler = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:134
 origErrorHandler = <function> defined @Interface/SharedXML/SharedBasicControls.lua:360
 hitInternalError = false
 CreateErrorFrame = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:544
 num = 0
 SanitizeString = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:518
 AddonBlockedHandler = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:502
 GetStackLevelInfo = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:344
 ParseLocals = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:396
 ignoreErrors = false
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:478
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface/AddOns/TradeSkillMaster/LibTSM/Service/ErrorHandler.lua:313
}
MAX_STACK_DEPTH = 50
OLD_TSM_MODULES = <table> {
 1 = "TradeSkillMaster_Accounting"
 2 = "TradeSkillMaster_AuctionDB"
 3 = "TradeSkillMaster_Auctioning"
 4 = "TradeSkillMaster_Crafting"
 5 = "TradeSkillMaster_Destroying"
 6 = "TradeSkillMaster_Mailing"
 7 = "TradeSkillMaster_Shopping"
 8 = "TradeSkillMaster_Vendoring"
 9 = "TradeSkillMaster_Warehousing"
}

**Comment by kemayo** [comment]
Oh, oops, I fixed that one back in 2a3db8e last week, but didn't make a release for it. I might as well do that now.
